{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.programs.niri;
in
{
  options.programs.niri = {
    enable = lib.mkEnableOption "niri";

    package = lib.mkPackageOption pkgs "niri" {
      nullable = true;
      extraDescription = ''
        Set to `null` to not add any niri package to your path.
      '';
    };

    settings = lib.mkOption {
      type =
        with lib.types;
        let
          valueType =
            nullOr (oneOf [
              bool
              int
              float
              str
              (attrsOf valueType)
              (listOf valueType)
            ])
            // {
              description = "KDL value";
            };
        in
        attrsOf valueType;
      default = { };
      example = lib.literalExpression ''
        {
          # str/num/bool → single argument
          screenshot-path = "~/Screenshots/%Y-%m-%d %H-%M-%S.png";
          layout.gaps = 8;
          layout.shadow.draw-behind-window = true;

          # {} → leaf node
          prefer-no-csd = {};
          input.touchpad.tap = {};

          # _props → named properties: offset x=0 y=5
          layout.shadow.offset._props = { x = 0; y = 5; };

          # _children → ordered/repeated children
          layout.preset-column-widths._children = [
            { proportion = 0.33333; }
            { proportion = 0.5; }
          ];

          # _props + list args in binds
          binds = {
            "Mod+H".focus-column-left = {};
            "Mod+Return" = {
              _props.hotkey-overlay-title = "Open a Terminal";
              spawn = ["ghostty"];
            };
            "XF86AudioRaiseVolume" = {
              _props.allow-when-locked = true;
              spawn = ["wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@" "5%+"];
            };
          };

          # _args for repeated/parameterized top-level nodes
          _children = [
            { workspace._args = ["chat"]; }
            { workspace._args = ["dev"]; }
            # _args + children
            { output = { _args = ["eDP-1"]; scale = 2.0; }; }
            # nested _children + _props
            {
              window-rule._children = [
                { match._props = { app-id = "firefox"; at-startup = true; }; }
                { open-on-workspace = "dev"; }
              ];
            }
          ];
        }
      '';
      description = ''
        Configuration added to {file}`$XDG_CONFIG_HOME/niri/config.kdl`.
        See <https://niri-wm.github.io/niri/Configuration%3A-Introduction.html> for the full list of options.
      '';
    };

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra configuration lines added to {file}`$XDG_CONFIG_HOME/niri/config.kdl` after the config generated from the options.";
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      (lib.hm.assertions.assertPlatform "wayland.windowManager.niri" pkgs lib.platforms.linux)
    ];

    home.packages = lib.optional (cfg.package != null) cfg.package;

    xdg.configFile."niri/config.kdl" =
      let
        toKDL = lib.hm.generators.toKDL {
          escapeBackslashes = true;
          escapeTabs = true;
        };
        settings = lib.removeSuffix "\n" (toKDL cfg.settings);
        configLines = lib.concatStringsSep "\n" (
          lib.filter (line: line != "") [
            settings
            cfg.extraConfig
          ]
        );
      in
      lib.mkIf (configLines != "") {
        source = pkgs.writeTextFile {
          name = "niri-config.kdl";
          text = ''
            // Generated by Home Manager.
            ${configLines}
          '';
          checkPhase = lib.optionalString (cfg.package != null) ''
            ${lib.getExe cfg.package} validate --config "$target"
          '';
        };
      };
  };
}
