name: Update Flake Packages

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flake-packages:
    name: Update Flake Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Set up Cachix
        uses: cachix/cachix-action@v17
        with:
          name: ${{ secrets.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run nix-update for niri-unstable
        run: nix run nixpkgs#nix-update -- --flake --version=branch packages.x86_64-linux.niri-unstable

      - name: Run nix-update for xwayland-satellite-unstable
        run: nix run nixpkgs#nix-update -- --flake --version=branch packages.x86_64-linux.xwayland-satellite-unstable

      - name: Create pull request
        id: pr
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: nix-update/bump-packages
          commit-message: "nix-update: bump unstable packages"
          title: "nix-update: bump unstable packages"
          body: "Automated bump of unstable packages via `nix-update`."

      - name: Push niri-unstable to Cachix
        if: steps.pr.outputs.pull-request-number != ''
        run: nix build -L .#niri-unstable --print-out-paths | cachix push ${{ secrets.CACHIX_CACHE_NAME }}

      - name: Push xwayland-satellite-unstable to Cachix
        if: steps.pr.outputs.pull-request-number != ''
        run: nix build -L .#xwayland-satellite-unstable --print-out-paths | cachix push ${{ secrets.CACHIX_CACHE_NAME }}

      - name: Auto-merge nix-update PR
        if: steps.pr.outputs.pull-request-number != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge ${{ steps.pr.outputs.pull-request-number }} --squash --delete-branch
